import { ORDER_STATUS } from './constants.js';

const TABLE = Object.freeze({
  DRAFT: Object.freeze({
    SUBMIT: ORDER_STATUS.NEEDS_INFO,
    REQUIRE_REVIEW: ORDER_STATUS.MANUAL_REVIEW,
    READY_FOR_PAYMENT: ORDER_STATUS.AWAITING_PAYMENT,
  }),
  NEEDS_INFO: Object.freeze({
    REQUIRE_REVIEW: ORDER_STATUS.MANUAL_REVIEW,
    READY_FOR_PAYMENT: ORDER_STATUS.AWAITING_PAYMENT,
  }),
  MANUAL_REVIEW: Object.freeze({
    NEEDS_INFO: ORDER_STATUS.NEEDS_INFO,
    READY_FOR_PAYMENT: ORDER_STATUS.AWAITING_PAYMENT,
    CANCEL: ORDER_STATUS.CANCELLED,
  }),
  AWAITING_PAYMENT: Object.freeze({
    PAYMENT_SUCCEEDED: ORDER_STATUS.CONFIRMED,
    CANCEL: ORDER_STATUS.CANCELLED,
  }),
  CONFIRMED: Object.freeze({ ASSIGN: ORDER_STATUS.ASSIGNED, CANCEL: ORDER_STATUS.CANCELLED }),
  ASSIGNED: Object.freeze({
    START: ORDER_STATUS.IN_PROGRESS,
    UNASSIGN: ORDER_STATUS.CONFIRMED,
    CANCEL: ORDER_STATUS.CANCELLED,
  }),
  IN_PROGRESS: Object.freeze({ COMPLETE: ORDER_STATUS.COMPLETED }),
  COMPLETED: Object.freeze({}),
  CANCELLED: Object.freeze({}),
});

export const transitionOrder = (current, event) => TABLE[current]?.[event] ?? null;
